const input = `LLLLLLLLLLLLLLL.L..LLLLLL.LLLLLLLLL.LLLLLL.LLLLLLL.LLLLLLL.LLLLLL.LLLLLLLLL.LLLL...LLLLLLLLLLL
LLLLLL.LLL.LLLLLLL.LLLLLL.LLLLLLLLL.LLLLLLLL.LLLLL.LL.LLLLLL..LLLLLLL.LLLLL.LLLL.LLLLLLLLLLLLL
LLLLL.LL.LLLLLLLLL.LLLLLLLLL.LLLLLL.LLLLLLLL.LLLLL.LLLLLLLLL.LLLLLLLL.LLLLLLLLLL.LLLLLLLLLLLLL
LLLLLLLL.LLLLLLLLLLL.LLLL.LLLLLLLLL.LLLLL.L.LLLLLL.LLLLLLLLL.LLLLLLLL.LLLLL.LLLL.LLLLLLLLLLLLL
.LLLLLLL.LLLLLLLLL.LLLLLLLLLLLLLLLL.LLLLLLLLLLLLLL.LLLLLLLLL.LLLLLLLLLLLLLL.LLLLLLLLLLLLLLLLLL
LLLLL.LLLLLLLLLLLL.LLLLLLLLLLLLLLLL..LLLLLLL.L.LLLLLLLLLLLLLLLLLLL.LL.LLLLLLLLLL.LLLLLLLLLLLLL
.LL.LLLL..LLLLLLLLLLLLLLL.LLLLLLL.LLLLLLLLLLL.LLLL.LLLLLLLLL.LLLLLLLLLLLLLL.LL.LLLLLLLLLLLLLLL
LLLLLLLL.LLLLLLLLL.L.LLLL.LLLLLLLLL...LLL.LL.L.LLL.LLLLLLLLL.LLLLLLLL.LLLLLLLLLLLLLLLLLLL.LL.L
LLL.LLLL.LLLLLLLLL.LLLLLL.LLLL.LLLL.LLLLLLLL..LLLL.LLLLLLLLL.LLLLLLLLLLLL.L.LLLL.LLLLLLLLLLLLL
.LLLLLLL.LLLLLLL.L.LLLLLL.LLLLLLLLL.LLLLLLLL.LLLLLLLLLLLLLLL.LLLLLLLL.L..LLLLLLL.LLLLLLLLLLLLL
..L......L.L..L.LL.LL....L......L.L.L..LL....L............L..L.LLL..L..LL.LL...............L..
LLLL.LLL.LLLLLLLLL.LLLLLLLLL.LLLLLLLLLLL.LLL.LLLLL.L.LLLL.LL.LLLLLLLL.LLLLL.LLLLLLLLLLLLLLLLLL
LLLLLLLL.LLLLLLLLL.LLLLLL.LLLLLLL.L..LLLLLL..LLLLLLLL.LLLLLLLLLLL.LLL.LLLLL.LLL.LLLL.LLLLLLLLL
LLLLLLLLLLLLLLL.LL.LLLLLL.LLLL.LLLL.LLLLLLLL.LLLLL.LLLLLLLLLLLLLLLLLL.LLLLL.LL.L..LLLLLLLLLLLL
LLLLLLLLLLLLLLLLLLLLLLLLL.LLLLLLLLL.LL.LLLLL.LLLLLLLLLLLLLLL.LLLLLLLL.LLLLL.LLLL.LLLLLLLLLLLLL
LLLLLLLL.LLLLLLL.L.LLLL.LLLLLLLLLLL.LLLLLLLL.LLLLLLLLLLLLLLL.LLLLLLL..LLLLL.LLL.LLLLLLLLLLLL.L
LLLLLLLL.LLL.LLLLL.LLLLLL.LLLLLLLLLLLLLLLLLLLLL.LL.LLLLLL.LL.LLL.LLLL.LLLLLLLLLL.LLLLLLLLLL.LL
LL.LLLLLLLLLLLLLL..LLLLLL.LLLLLLLLLLLLLLLLLL.LLL.L.LLLLLLLLLLLLLLLL.LL.LLLL.LLLL.LLLL.LLLLLLLL
..L......L....L...L..LLL..L.LL.....LLL.LL.L..LLLLLL...L.LL.LL...L....L..LLL.LLL..L...L........
LLLLLLLLLLLLLLLL.L.LLLLLL.LLLLLLLLL.LLLLLLLL.LLLLL.LLLLLLLLL.LL.LLLLL.LLLLLLLLLL.LL.LL.LLLLLLL
LLLLLLLL.LLL.LLLLLLLLLLLL.LLLLLLLLL.LLLLLLLL.LLLLL.LLLLL.LLL.LLLLLLLLLLLLLL.LLLLL.LLLLLLLL.LLL
L.LLLLLLLLLLLLLLLL.L.LLLL.LLLLLLL.L.LLLLLLLLLLLLLLLLLLLLLLLL.LLLL.LLLLLLLLL.LLLLLLLLLLLLLLLLLL
LLLLLLLL.LLLLLLLLL.LLLLLLLLLLLLLLLL.LLLLLLLLLL.LLLLL.LLLLLLL.L.LLLLLL.LL.LL.LLLL.LLLLLLLLLLLLL
LL...........L..L.....L..L.....L......L..L.LL.L....LL..L.L...L..LLLL....LL.LL.......LLL......L
LLLLLLLL.LLLLLLLLLLLLLLLLLL.LLLLLLL.LLLLLLLL.LLLLLLLLLLLLLLL.LL.LLLLLLLLLLL..LLL.LLLLLLLLLLLLL
LLLLLLLLLLLLLLLLLLLL.LLLL.LLLL.LLLL.LLLLLLLLLLLLLL.LLLLLLLLL.LLLLLLLL.LLLLLLLLLL.LLLLLLLLLLLLL
LLLL.LLL.LLL.LLLLLLLLLL.L..LL.LLLLLLLLLLLLLL.LLL.L.L.LLLLLLLLLLLLLLLL.LLLLLLLLLLLLLLLLLLLLLLLL
LLLLLLLL.LLLLLLLLL.LLLLLLLL.LLLLLLLLLLLLLLL.LLLLLL.LLLLLLLLL.LLL.LLLLLLLL.L.LLLL.LLLLLLLLLL.LL
LLLLLLL.LLLLLLLLLL.LLLLLL.LLLLLLLL..LLLLLLL..LLLLLL.LLLLLLLLLLLLLLL.L.LLLLLLLLLL..LLLLLLLLLLLL
.LLLLLLLLLLLLLLLLL.LLLLLLLLLLLLLLLLL.LLLLLLL.LLLLLLLLLLLLLLL.LLLLLLLL.L.LLL.LLLLLLLLLLLLLLLLLL
LLLLLLLL.L.LLLLLL.LLLLLLLLLLLL.LLLL..LLLLL.LLLLLLL.LLLLLLLLL.LLLLLLLLL.LLLL.LLLLL.LLLLLLLLLLLL
L.L..LLLL..L...L.L..L..L.LL.L..L....LL.L...L..L.L.LL......LLL.L.L..L.......L...LL...LLLL....L.
LL.LLLLL.LLLLLLLLLLLLLLLL.LLLLLLLLL.LLLLLLLLLLLLLL.LLL.LL.L..LLLLLLLLLLL.LLLLLLL.LLLLLLLLLLLLL
.LLLLLLLLLLLLLLLLL..LLLLLLLLLLLLLLL.LLLLLLLL.LLLLL.LLLLLLLL..LLLLLLLLLL.LLLLLLLLL.LLLLLLLLLLLL
LLLLLLLL.LLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL.LL.LLLLL.LLLLLLLL.LL..LLLLLLLLL.L.LLLLLLLLLLLLLLLLLL
LLLLLLLL..LLLLLLLL.LLL.LL.LLLLLLLLL.LLLLLLLL.LL.LL.LLLLLLLLL.LLLLLLLL.LLLLL.LLLL.LLLLLLLLLLLLL
LLLLLLLLLLLLLLLLL..LLLLLL..LLLLLLLL.LLLLLLLL..LLLL..LLLLLLLL.L.LLLLLL.L.LLLLLLLL.LLLLLLLLLLLLL
L.LL...LL..L......L..L..L..L.LL...LL...L....LL..L..........L..L.L.LL.L......L.........L.L.L...
LLLLLLLL.LLLLLLLLL.LLLLLL.LLLLLLLLL.LLLLLLLLLLLLLLLLLL.LLLLL.LLLLLLLL.LLLLLL.LLL.LLLLLLLLLLLLL
LLLLLLLL.LLLLLLLLL.LLLLLL.LLLLLLLLL.LLLLLLLLLLLLLLLLLLLLLLLL.LLLL.LLLLLLLLLLLLLL.LLLLLLLL.LLLL
LLLLLLLLLLLLLLLLL.LLL.LLLLLLLLLLLL..LL.LLL.LLLLLLLLLLLLLLLLL.LLL.L.LL.LLLLLLLLLL.LLLLLLLLLLLLL
LLLLLLL..LLLLLLLLL.LLL.LL.LLLLLLLLL.LLL.LLLL.LLLLLLLLLLLLLLLLLLLLLLLL.LLLLL.LL.L.LLLL.LLLLLLLL
LLLLLLLLLLLLLLLLLL.LLLLLL.LLLLLLLL.LLLLLLLL..LLLLL.LLLLLLLLL.LLLLLLLL.L.LLL.LLLL.LLLLLLLLLLLLL
LLLLLLLL.LLLLLLLLLLLLLL...LLLLLLLLL.LLLLLLLLLLLLLL.LLLLLLLL..LLL.LLLLLLLLLL.LLL.LLLLLLLLLLLLLL
LLLLL.LL.LLLLLLLLL.LLLLLL.LLLLLLLLL.LLLLLLLL.LLLLLLLLLLLLLLL.LLLLLLL.LLLLLLLLLLLLLLLLLLLLLLLLL
LLLLLLLLLL.LLLLLLL.LLLLLLLLLLLL.LLLLLLLLL.LL.LLLLL.LLLL.LLLLLLL.LLLLLLLLLLL.LLLL.LLLLL.LLLLLLL
LLLLLLLL.LLLLLLLLL.LLLLLL.LLLLLLLLL.LLLLLLLLLLLL.L.LLLL.LLL..LL.LLLLLLLLLL..LLLLLLLLLLLLLLLLLL
.L.L..LL....L.LLLL.....LL.L...L.L..LL..LL........LL..L.L..L....L.LLL....L..L.L..L.LL..L.....L.
LLLLLLLLLLLLLLLLLL.LLLLLL.LLLLLLLLL.LLLLLLLLLL.LL.LLLLLLLLLL.LLLLLLLL.LLLL..LLLL.LLLLL.LLLL.LL
LLLLLLLL.LLLLL.L.L.LLLLLL.LLLLLLLLL.LLLLLLLL.LLLLLLLLLLLLLLLLLLLLLLLL.LLLLL.LL.L.LLLLLLLL.LLLL
LLLLLLLL.LLLLLLLLLLLLLLLL.LLLLLLLLL.LLLLLLLL.LLLLL.LLLLLLLLLLLLLL.LLL.LLLLL.LLLL.LLLLLLLLLLL.L
LLLLLLLL.LLLLLLLLLL.LLLLLLLLLLLLLLL.LLLLLLLL.LLLLLLLLLLLLLLL.LLLL.LLL.LLLLL.LLL..LLLLLLLLLLLLL
LLLLLLLL.LLLLLLLLL.LLL.L.LLLLLLLLLLLLLLLLLLL.LLLLLLLLLL.LLLL.LLLLLLLLLLLLLL.LLLLLLLLLL.LLLLLLL
LLLLLLLLLLLLLLLLLL.LLLLLL.LLLLLLLLL.LLLLLLLL.LLLLL.L.LLLLLLLLLLLLL.LLLLLLLL.LL.LL.LLLLLLLLLLLL
LLLLL.LL.LLLLLLLLLLLLLLLLLLLLLLLLLL.LLLLLLLL.LLLLL.LLLLLLLLLLLLLLLLLL.LLLLLLLLLL.LLLLLLLLLLLLL
LL.LL..L.LL.....LL..L.LLLL..........L.....L.L..LL..LLLL....L.........L.L...L...L....L...LL...L
LLLLLLLL.LLLLLLLL..LLLLL..LLLLLLLLL.LLLLLLLL.LLLLLLLLLLLLLLLLLLLLLLLL.LLLLL..LLL..LLLLLLLLLLLL
LLLLLLLLLLLLLLLLLL.LLLLLL.LLLLLLL.L.LLLLLLLLLLLLLL.LLLLLLLLL.LLLLLLLL.LLLLL.LL.L.L.LLLLLLLLLLL
LLLLLLLLL.LLLLLLLL.LLLLLLLLL.LLLLLL.LLLLLLL..LLLLLLLLLLLLLLL.LLLLLLLL.LLLLL.LLLLLLLL.LLLLLLLLL
L.LLLLLL.LLLL.LLLL.LLLLLL.LLLLLLLLL.LL.LLLLL.LLLLL.LLLLLLLLL.LLL.LLL.LLLL.LLLLLL.LLLLLLLLLLLLL
....L........L.....L.L.............L.L..L..LLLL.......L......LL.........L....L...L.LL..LL.LL.L
LLLLLLLL.LLLLLLLLLLLLLLLL.LLLLLLLLL.LLLLLLLL.LLLLL.LLLLLLLLL..LLLLLLL.LLLLL.LLLL.LLLLLLLLLL.LL
LLLLLLLL.LLLLLLL.L.LLLLLL.LLLLLLLLL.LLLLLLLL.LLLLL.LLLLLLLLL.L.LLLLLLLLLLLL.LLLL.LLLLLLLLLL.LL
LLLLLLLLLLLLLLLL.L.LLLLLL..LLLLLLLL.LLLLLLLL.LLLLL.LLLLLLLL..LLLLLLLL.LLLLL.LLL.LLLLLLLLLLLLLL
LLLL.LLL.L.LLLLLLL.LLLLL.LLLLLLLLLL.LLLLLLLL.LLLLL.LLLLLLLLLLLLLLLLLL.LLLLL.LLLL.LLLLLLLLLLLLL
LLLLLLLL.LLLLLLLLL.LLLLLL.LLLLLLLLLLLLLLLLLL.LLLLL.LLLLL.LLLLLLLLLLLL.LLLLL.LLLLLLLLLLLLLLLLLL
.L..LL.LL...LLL..L..L..L.L..LL......LLLL......L...LLL...L..L...LL....LL....LL.LLLLL...L.L.L..L
LLLLLLLL.LLL.LLLLL.LLL.LL.L.LLLLLLL.LLLLLLL.LL.LLLLLLLLLLLLL.LLLLLLLLLL.LLL.LLLL.LLLLLLLLLLLL.
LL.LLL.L...LLLLL.L.LLLL.L.LLLLLLLLLLLLLLLLLLLLLLLL.LLLLLLLLL.L.LLLLLLLLLLLL.LLLLLLLLLLLLLLLLLL
LLLLLLLL.LLLL.LL.L.LLLLLL.LLLLLLLLL.LLLLLLLL.LLLLL.LLLLL.LLLLL.LL.LLLLLL.LLLLLL.LLLLLLLLLL.LLL
LL.LLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL.LLLLL.LLLLLLLL.LLLLLLLLLLLLLLLLLL.LLLLL.LLLL.LLLLL..LLLLLL
LLLLLLLL..LLLLLLL..LLLL.L.LLLLLLLLLL.LLLLLLLLLLLLLLLLLLLLLLL.LLLLLLLL.L.LLL..LLL.LLLLLLLLLLLL.
LLLLLLL..LLLLLLLLL.LLLLLL.LLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL.LLLL.LLLL.LLLLLLLL
LLLLLLL..LLLLL.LLL.LLLLLL.LLLLLLLLL..LLLLLLLLLLLLL.LLLLLLLLLLLLLLLLLLLLLLLL.LLL.LLLLLLLL.LLLLL
LLLLL.LLLLLLLLLLLL.LLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL.LLLLLLLLL.LLLLLLLL.LLLLL..LLL.LLLLLLLLLLLLL
LLLLLLLLLLLLLLLLLL.LL.LLLLLLL.LLLLL.L.LLLLLLLLLLL..LLLLL.LLL.LLLLLLLL.LLLLLLLLLL.LLLLLLLLLL.LL
.....LLL..L..L...LL..L.LL.LLLL....L.L.LL.L.L......LLLL..L..LL.L......L.LL.....L...L...L..LLL..
.LLLLLLL.LLLLLLLLLLLLLL.L.LLLLLLLLL.LLLLLLLLL.LLLL.LLLLLLLLL.LLLLL.LL.LLLLL.LLLL.LLLLLLLLLLLLL
LLLL.LLL.LL.LLLLLL.LLLLLLLLLLLLLLLLLLLLLLL.L.LLL.L.LLLLLLLLLLLLLLLLLL.LLLLLLLLLL.LLLLLLLLLLLLL
LLLLLLLL.LLLLLLLLLLLLLLLL.LLLLLLLLLLLL.LLLLLLLLLLL.LLLLLLLLLLLLLLLLLLLLLLLLLLLLL.LLLLLLLLLLLLL
LLLLLLLL.LLLLLLLL..LLLLLL.LLLLLLLLL.LLLLLLLLLLL.LL.LLLLLLLLLLLLLLLLLLLL.LLL.LLLLL.LLLLLLLLLLLL
LLLLLLLL.LLLLL.LLL.LLLLLLLLLLLLLL.L.LLLLLLLL.L.LLLLLL.LLLLLL.LLLLLLLLLLLLLL.LLLL.LLLLLLLLLLLLL
LLLLLLLL.LLLLLLLL.LLLLLLLLLLLLLLLLL.LLLLLLLL.LLLLLLLLLLLLLLLLLLLLLLLL.LL.LL.LL.LLLLLLLLLLLL.LL
LLLLLLLL.LLLLLLLLLL.LLLLLLLLLLLLLLL.LLLLLLLL.LLLLL.LLLLLLLLL.LLLLLLLL.LLLLL.L.LL.LLLLLLLLLLLLL
L.L.L.......L.LLL.L.L..L.LLL.L..L...LLLL.L.L.....L...L..L........L...LL...L..L...LLLL..L..L...
LLLLLLLLLLLLLLLLLLLLLLLLL.LLLLLLLLL.LLLLLLLL.LLLLL.LLLLLLLLL.LLLLLLL..LLLLLLLLLLLLL.LLLLL..LLL
LLLLLLLL.LLLLLLLLL.LLLLLL.LLLLLLLLL.LLLLLLLL.LLLLLLLLLLLLLLL.LLLLLLLLLL.LLL..LLL.LLLLLLL.LLLLL
LLLLL.LL.LLLL.LL.L.LLL.LL.LLLL.LLLL.LLLLLLLL.LLLLL.LLLLLL.LL.LLLLLLLLLLLLLL.LLLLLLLLLLLLLLLLLL
LLLLLLLLLLLLLLLLL.LLLLLLL.LLLLLLLLLLLLLLLLLL.LLLLL.LLLLLLLLL.LLLLLL.L.LLLLLLLLLL.LLLLLLLLLLLLL
LLLLLLLL.LLLLLLLLL.LLLLLLLLLLLLLLLL.LLLLLLLL.LLLLL.LLLLLLLLLLLLLLLLLL.LLL.L.LLLL.LLLLLLLLLLLLL
.LLLLL.L.LLLLLLLLLLL.LLLLLLLLLLLLLLLLLLLLLLL.LLLLL.L.LLLLLLLL.LLLLLLL.L.LLL.LLLLLLLLLLL.LLLLLL
LLLLLLLL.LLLLLLLLL.LLLLLLLLLLLLLLLL.LLLLLLLL.LLLLLLL.LLLLLLL.LLLLLLLLLLLLLL.LLLL.LLLL.LLLLLLLL
LLLLLLLL..LLLLLLLL.LLLLL..LL.LLLLLL.LLLLL.LLLL.LLLLLLLLLLLLLLLLLLLLLL.LLLLL..LLL.LLLLLLLLLLLLL`;

const seats = input.split('\n').map(row => row.split(''));

const EMPTY_SEAT = 'L';
const OCCUPIED_SEAT = '#';
const FLOOR = '.';

const countOccupiedSeats = currentSears => currentSears.flatMap(m => m).filter(m => m === OCCUPIED_SEAT).length;
const getPosition = (currentSeat, x, y) => x === false || y === false ? false : currentSeat[y][x];
const getAdjacentSeats = (currentSeat, x, y) => {
  const xplus = x === (currentSeat[0].length - 1) ? false : x + 1;
  const xminus = (x === 0) ? false : x - 1;

  const yplus = y === (currentSeat.length - 1) ? false : y + 1;
  const yminus = (y === 0) ? false : y - 1;

  const adjacentSeats = [
    getPosition(currentSeat, x, yminus),
    getPosition(currentSeat, xplus, yminus),
    getPosition(currentSeat, xplus, y),
    getPosition(currentSeat, xplus, yplus),
    getPosition(currentSeat, x, yplus),
    getPosition(currentSeat, xminus, yminus),
    getPosition(currentSeat, xminus, y),
    getPosition(currentSeat, xminus, yplus),
  ];

  return adjacentSeats;
};

const simulatePlacement = (currentSeats) => {
  const newSeats = [];

  for (let x = 0;x < currentSeats[0].length; x++) {
    const newRow = [];
    for (let y = 0;y < currentSeats.length; y++) {
      const currentSeat = currentSeats[y][x];
      const adjacentSeats = getAdjacentSeats(currentSeats, x, y);

      if (currentSeat === EMPTY_SEAT && !adjacentSeats.includes(OCCUPIED_SEAT)) {
        newRow.push(OCCUPIED_SEAT);
      } else if (currentSeat === OCCUPIED_SEAT && adjacentSeats.filter(seat => seat === OCCUPIED_SEAT).length >= 4) {
        newRow.push(EMPTY_SEAT);
      } else {
        newRow.push(currentSeat);
      }
    }

    newSeats.push(newRow);
  }

  return newSeats;
};

let newSeats = seats;

let beforeOccupiedSeats, afterOccupiedSeats = 0;

do {
  beforeOccupiedSeats = countOccupiedSeats(newSeats);
  newSeats = simulatePlacement(newSeats)
  afterOccupiedSeats = countOccupiedSeats(newSeats);
} while (beforeOccupiedSeats !== afterOccupiedSeats);
console.log(afterOccupiedSeats);

// part 2
const getSeatInDirection = (currentSeats, x, y, newX, newY) => {
  let seat, meetBorder;

  while (!meetBorder && !seat) {
    if (x + newX === currentSeats[0].length || x + newX < 0 || y + newY === currentSeats.length || y + newY < 0) {
      meetBorder = true;
    } else {
      x += newX;
      y += newY;

      if (currentSeats[y][x] !== FLOOR) {
        seat = currentSeats[y][x];
      }
    }
  }
  return seat;
};

const getVisibleSeats = (currentSeat, x, y) => {
  const adjacentSeats = [
    getSeatInDirection(currentSeat, x, y, 1, -1),
    getSeatInDirection(currentSeat, x, y, 1, 0),
    getSeatInDirection(currentSeat, x, y, 1, 1),
    getSeatInDirection(currentSeat, x, y, 0, -1),
    getSeatInDirection(currentSeat, x, y, 0, 1),
    getSeatInDirection(currentSeat, x, y, -1, -1),
    getSeatInDirection(currentSeat, x, y, -1, 0),
    getSeatInDirection(currentSeat, x, y, -1, 1),

  ];

  return adjacentSeats;
};

const simulatePlacementPart2 = (currentSeats) => {
  const newSeats = [];

  for (let x = 0;x < currentSeats[0].length; x++) {
    const newRow = [];
    for (let y = 0;y < currentSeats.length; y++) {
      const currentSeat = currentSeats[y][x];
      const adjacentSeats = getVisibleSeats(currentSeats, x, y);

      if (currentSeat === EMPTY_SEAT && !adjacentSeats.includes(OCCUPIED_SEAT)) {
        newRow.push(OCCUPIED_SEAT);
      } else if (currentSeat === OCCUPIED_SEAT && adjacentSeats.filter(seat => seat === OCCUPIED_SEAT).length >= 5) {
        newRow.push(EMPTY_SEAT);
      } else {
        newRow.push(currentSeat);
      }
    }

    newSeats.push(newRow);
  }

  return newSeats;
};

let newSeatsPart2 = seats;
let beforeOccupiedSeatsPart2, afterOccupiedSeatsPart2 = 0;

do {
  beforeOccupiedSeatsPart2 = countOccupiedSeats(newSeatsPart2);
  newSeatsPart2 = simulatePlacementPart2(newSeatsPart2)
  afterOccupiedSeatsPart2 = countOccupiedSeats(newSeatsPart2);
} while (beforeOccupiedSeatsPart2 !== afterOccupiedSeatsPart2);

console.log(afterOccupiedSeatsPart2)